apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rhdh-gitlab-token.yaml
  - dynamic-plugins-root-pvc.yaml
  - dynamic-plugins-rhdh.yaml
  - app-config-rhdh.yaml
  - backstage.yaml
