apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}-dev
  namespace: openshift-gitops
spec:
  project: apps
  source:
    repoURL: ${{ values.gitopsRepoUrl }}
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.name }}-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
