apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.name }}-dev
resources:
  - ../../base
images:
  - name: PLACEHOLDER
    newName: ${{ values.quayNamespace }}/${{ values.name }}
    newTag: latest
