apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-gitlab-root-password
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
    files:
      - gitlab-root-password-job.sh
  - name: job-gitlab-domain-init
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
    files:
      - gitlab-domain-init-job.sh

resources:
  - gitlab-domain-init-job.yaml
  - gitlab-root-password-job.yaml
  - gitlab.yaml
